version: '3.8'

services:
  alb-analyzer:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/app/data/alb_analyzer.db
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL for production use
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: alb_analyzer
      POSTGRES_USER: alb_user
      POSTGRES_PASSWORD: alb_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles:
      - postgres

volumes:
  postgres_data: